x-cloud-config-generator-template: &cloud-config-generator-template
  build:
    context: ./docker/cloud-config-generator
  volumes:
    - ${PWD}/templates/cloud-config:/cloud-config-generator/templates
    - ${PWD}/generated/cloud-config:/cloud-config-generator/generated
    - ${PWD}/credentials/gateway:/cloud-config-generator/credentials
  profiles:
    - cloud-config

x-image-build-template: &image-build-template
  image: mkaczanowski/packer-builder-arm:latest
  volumes:
    - /dev:/dev
    - ${PWD}/ansible:/build/ansible
    - ${PWD}/cloud-init:/build/cloud-init
    - ${PWD}/packer:/build/packer
    - ${PWD}/build/image:/build/generated
    - ${PWD}/build/.packer_cache:/build/.packer_cache
    - ${PWD}/build/.packer_plugins:/build/.packer_plugins
  privileged: true

services:
  cloud-config-gateway1-generator:
    <<: *cloud-config-generator-template
    environment:
      SERVER_NAME: br-gateway1

  cloud-config-gateway2-generator:
    <<: *cloud-config-generator-template
    environment:
      SERVER_NAME: br-gateway2

  packer-init:
    image: mkaczanowski/packer-builder-arm:latest
    <<: *image-build-template
    command: >
      init -upgrade packer/build.pkr.hcl
    profiles:
      - packer-init

  gateway1-image-build:
    <<: *image-build-template
    command: >
      build --var-file=packer/br-gateway1.pkrvars.hcl packer/ -extra-system-packages=ansible
    profiles:
      - gateway1-image-build

  gateway2-image-build:
    <<: *image-build-template
    command: >
      build --var-file=packer/br-gateway2.pkrvars.hcl packer/ -extra-system-packages=ansible
    profiles:
      - gateway2-image-build